-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  role text check (role in ('parent', 'teen')),
  xp integer default 0,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for todos
create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  reward integer default 10,
  status text check (status in ('pending', 'completed', 'approved')) default 'pending',
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for todos
alter table todos enable row level security;

create policy "Todos are viewable by everyone."
  on todos for select
  using ( true );

create policy "Users can insert their own todos."
  on todos for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own todos."
  on todos for update
  using ( auth.uid() = user_id );
